### PR TITLE
Take screenshots beyond viewport without resizing

### LINKED ISSUE #81: Screenshots are white beyond the window size when using `setDeviceMetricsOverride`
Originally posted as https://github.com/rstudio/shinytest2/issues/161, but independent of `shinytest2`.

```
library(chromote)
b <- ChromoteSession$new()
b$Emulation$setDeviceMetricsOverride(width=1920, height=1080, deviceScaleFactor=1, mobile=FALSE)
b$Page$navigate("https://github.com/rstudio/chromote")
Sys.sleep(3)
b$screenshot()
```

<details>

screenshot

</details>

### PR DESCRIPTION
**Pull request by bersbersbers**
This closes #81 and *may* also help with https://github.com/rstudio/shinytest2/issues/136

### CODE REVIEW

**Comment by wch** [comment]
Interesting -- this should really simplify the screenshotting process. I believe that the `captureBeyondViewport` argument didn't exist when this code was originally written.

A couple things to watch out for:
* What happens if the page is smaller than the viewport?
* What happens when scrollbars are present?

**Comment by schloerke** [comment]
@wch Why was this PR closed?

**Comment by wch** [comment]
Oh oops, I must have accidentally clicked that.

**Comment by bersbersbers** [comment]
> I believe that the `captureBeyondViewport` argument didn't exist when this code was originally written.

Yes, this landet in Chrome 89, and the code I deleted refers to Chrome 72 and 75.

> * What happens if the page is smaller than the viewport?

Do you mean vertically, horizontally, both?

> * What happens when scrollbars are present?

I filed (in principle, unrelated) issues as the current implementation has problems in exactly these cases, see https://github.com/rstudio/shinytest2/issues/171 and https://github.com/rstudio/chromote/issues/84

**Comment by bersbersbers** [comment]
A few more points in addition:
- At least the *width* of current snapshots (992) is already larger than the minimum, compare https://github.com/rstudio/shinytest2/blob/91ff4e58cad2d09e0e90f50e06911b1f47aa85d9/tests/testthat/apps/hello/tests/testthat/_snaps/mac-4.1/app/001.png. It's true that the *height* may change with this PR, but as you say, unless it's specified what the result should be, I'd have trouble saying that the current behavior needs to be maintained.
- Taking smaller screenshots is always possible by specifying an element to screenshot.
- The comment above the code I deleted, while the code does make screenshots of smaller-than-viewport elements *smaller*, says its purpose is (only?) to *enlarge* screenshots where necessary, not to restrict the height of screenshots of small elements.

**Comment by bersbersbers** [comment]
All theoretical considerations aside, a short test reveals that chromote already renders "small" (short, narrow) web sites according the dimensions of the initial session, and that remains true with this PR:

```shell
git clone https://github.com/bersbersbers/chromote/
cd chromote

export URL="https://cran.r-project.org/bin/"
export BRANCH="main"
# export BRANCH="snapshot_without_resize"

git checkout $BRANCH
Rscript -e 'devtools::install(); b <- chromote::ChromoteSession$new(); b$Page$navigate(Sys.getenv("URL")); Sys.sleep(1); b$screenshot("snap.png")'
exiftool snap.png | grep -E "Width|Height"
```

```
Image Width                     : 992
Image Height                    : 1323
```

I have not tested how `shinytest2` may react to this change, but to me, this looks alright.

**Comment by wch** [comment]
> All theoretical considerations aside, a short test reveals that chromote already renders "small" (short, narrow) web sites according the dimensions of the initial session (probably because the HTML element fills the available viewport), and that remains true with this PR:

The page you were using for testing is this one: https://cran.r-project.org/bin/
When I look at it in the web browser, the `<body>` takes the full height of the viewport. However, other pages don't work this way. For example, this shiny app: https://gallery.shinyapps.io/001-hello/?showcase=0

With this app, the body does not fill the height of the viewport. And currently, screenshots of that page result in a PNG that is 463 pixels tall.


```R
library(chromote)
b <- chromote::ChromoteSession$new()
b$Page$navigate("https://gallery.shinyapps.io/001-hello/?showcase=0")
# Wait for a few seconds
b$screenshot()
```

**Comment by wch** [comment]
> At least the width of current snapshots (992) is already larger than the minimum....

It is possible (though uncommon) for a web page to have the `width` set to a value other than the viewport width. For example, if you have `<body style="width: 500px">`, then the body width would be 500 pixels.

One thing that could be done is to trim the screenshot to the size of the body _after_ getting the screenshot from Chrome (if the body is smaller than the viewport).

The goal of the screenshot method is to get an image of the web page; if we are willing to capture areas that are outside of the viewport, then we should be willing to trim the image to match the web page.

**Comment by wch** [comment]
Now that we've been looking at the code more closely, it appears that the `is.null(cliprect)` code path may already clip the screenshot to the correct dimensions, although this needs to be tested.

**Comment by schloerke** [comment]
Been using this PR for the day and have not run into issues. I'd like to merge it as it solves a few issues in `{shinytest2}`

**Comment by schloerke** [comment]
@bersbersbers Has this PR resolved the pixel diffs being produced in {shinytest2}?

**Comment by schloerke** [comment]
Merging before feedback. My local usage as been good!

**Comment by bersbersbers** [comment]
> @bersbersbers Has this PR resolved the pixel diffs being produced in {shinytest2}?

Sorry for the late reply, I was OOO for a bit. With `chromote` v0.1.0 from CRAN and a current `shinytest2` from GitHub, I have not seen this issue any more, no. A lot of other packages have been updated in the meantime, so I am not able to pinpoint it to this specific PR, but it seems likely to me that it did in fact resolve it.

**Comment by schloerke** [comment]
@bersbersbers Yay! Glad to hear

**Pull request merged**
