### PR TITLE
Add targetId to Chromote$new_session() args

### PR DESCRIPTION
**Pull request by alandipert**
I forgot to add this in #17.

### CODE REVIEW

**Comment by alandipert** [comment]
@wch Note there's also https://github.com/rstudio/chromote/blob/add-targetId-new_session/R/chromote_session.R#L140-L142 which I wasn't sure what to do with. It looked wrong to me (`wait_` isn't the first argument to `Chromote$new_session()` anymore). Should it have the same arguments as `Chromote$new_session()` including the new `targetId`?

**Comment by wch** [comment]
I think the existing code works correctly -- the waiting is done below:
https://github.com/rstudio/chromote/blob/master/R/chromote.R#L124

The purpose of that is to make sure that it returns the correct thing: when `wait_=FALSE`, return the ChromoteSession object. When `wait_=TRUE`, return a promise that resolves to a ChromoteSession object.

One thing to be aware of is that `ChromoteSession$new()` is different -- it always returns the ChromoteSession object, because of how R6 works. 

You could change `new_session` to be a little different, but overall I don't think it's that much simpler.

```R
    new_session = function(width = 992, height = 774, targetId = NULL, wait_ = TRUE) {
      if (wait_) {
        ChromoteSession$new(self, width, height, targetId, wait_ = TRUE)
      } else {
        # ChromoteSession$new() always returns the object, but the
        # initialization is async. To properly wait for initialization, we
        # need to call b$init_promise() to get the promise; it resolves
        # after initialization is complete.
        session <- ChromoteSession$new(self, width, height, targetId, wait_ = FALSE)
        self$wait_for(session$init_promise())
      }
    },

**Comment by wch** [comment]
Regarding `wait_` as the first param: it matches because the other args are named, but I agree it would make more sense to pass it as a named arg as well.

**Comment by alandipert** [comment]
I think what has me confused is that `Chromote` and `ChromoteSession` both have `new_session()` methods, but they have different argument lists.

The `ChromoteSession$new_session()` seems to assume that `self$parent` is a a `ChromoteSession` the `new_session()` of which expects `wait_` as the first argument, but an "original" `ChromoteSession` will have a `self$parent` of a `Chromote` object as returned by `default_chromote_object()`, the `$new_session()` of which expects `width` first.

It seems like a bug to me that these methods must call eachother with all arguments named in order to work correctly, but I feel like I could also be missing something basic named arguments.

**Comment by alandipert** [comment]
Nevermind, I think I understand what's going on. I'll rearrange the arguments and we can see how it looks.

**Comment by alandipert** [comment]
Closing in favor of #19

**Pull request closed without merging**
