### PR TITLE
Soft import `curl` package

### LINKED ISSUE #37: curl package is required for chromote to work
Currently **curl** is not among the imported package in **chromote**. It is not a direct dependency and **chromote** uses **jsonlite** which need **curl** when used on urls. **curl** is a suggested package of **jsonlite** only. 

With a basic installation of **chromote**, we can't run the basic example without **curl**. 
See the reprex below where we install **chromote** in a clean library with no other package. 

```r
> callr::r(function() {withr::with_temp_libpaths({
+     install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
+     pak::pak("rstudio/chromote")
+     library(chromote)
+     b <- ChromoteSession$new()
+     b$Browser$getVersion()
+     }, action = "replace")}, show = TRUE)
Installing package into 'C:/Users/chris/AppData/Local/Temp/RtmpW2ZuT8/temp_libpath1bc407f653bb4'
(as 'lib' is unspecified)
essai de l'URL 'https://r-lib.github.io/p/pak/dev/bin/windows/contrib/4.0/pak_0.1.2.9001.zip'
 length 13729056 bytes (13.1 MB)
\
downloaded 13.1 MB

package 'pak' successfully unpacked and MD5 sums checked
-
The downloaded binary packages are in
	C:\Users\chris\AppData\Local\Temp\RtmpW2ZuT8\downloaded_packages
\ Loading metadata database ... done
 
> Will install 12 packages.
> Will download 9 CRAN packages (11.53 MB), cached: 2 (2.45 MB).
> Will download 1 package with unknown size.
+ chromote    0.0.0.9003 [bld][cmp][dl] (GitHub: ba9bffc)
+ fastmap     1.1.0      [dl] (432.08 kB)
+ jsonlite    1.7.2      [dl] (541.93 kB)
+ later       1.2.0      [dl] (674.08 kB)
+ magrittr    2.0.1      [dl] (235.91 kB)
+ processx    3.5.2      
+ promises    1.2.0.1    [dl] (2.13 MB)
+ ps          1.6.0      [dl] (407.25 kB)
+ R6          2.5.0      [dl] (84.14 kB)
+ Rcpp        1.0.6      [dl] (3.11 MB)
+ rlang       0.4.11     
+ websocket   1.4.0      [dl] (3.92 MB)
i Getting 9 pkgs (11.53 MB) and 1 pkg with unknown size, 2 (2.45 MB) cached
v Cached copy of chromote 0.0.0.9003 (source) is the latest build
v Cached copy of R6 2.5.0 (windows) is the latest build
v Cached copy of Rcpp 1.0.6 (windows) is the latest build
v Cached copy of fastmap 1.1.0 (windows) is the latest build
v Cached copy of jsonlite 1.7.2 (windows) is the latest build
v Cached copy of later 1.2.0 (windows) is the latest build
v Cached copy of magrittr 2.0.1 (windows) is the latest build
v Cached copy of promises 1.2.0.1 (windows) is the latest build
v Cached copy of ps 1.6.0 (windows) is the latest build
v Cached copy of websocket 1.4.0 (windows) is the latest build
v Installed R6 2.5.0  (232ms)
v Installed fastmap 1.1.0  (228ms)
v Installed jsonlite 1.7.2  (284ms)
v Installed later 1.2.0  (356ms)
v Installed magrittr 2.0.1  (416ms)
v Installed ps 1.6.0  (464ms)
v Installed processx 3.5.2  (589ms)
v Installed rlang 0.4.11  (629ms)
v Installed promises 1.2.0.1  (704ms)
v Installed websocket 1.4.0  (745ms)
v Installed Rcpp 1.0.6  (921ms)
i Packaging chromote 0.0.0.9003
v Packaged chromote 0.0.0.9003 (604ms)
i Building chromote 0.0.0.9003
v Built chromote 0.0.0.9003 (5.4s)
v Installed chromote 0.0.0.9003 (github::rstudio/chromote@ba9bffc) (84ms)
v 1 + 11 pkgs | kept 0, updated 0, new 12 | downloaded 0 (0 B) 11.7s
Error : Required package curl not found. Please run: install.packages('curl')
Error: callr subprocess failed: Required package curl not found. Please run: install.packages('curl')
Type .Last.error.trace to see where the error occurred
```

Maybe **curl** should be made a hard dependency of **chromote** as it seems required for it to work ?

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #37

### CODE REVIEW

**Comment by schloerke** [comment]
# Reprex of fix

Using current master commit...

``` r
remove.packages("curl")
#> Removing package from '/Library/Frameworks/R.framework/Versions/4.0/Resources/library'
#> (as 'lib' is unspecified)
# current master commit
remotes::install_github("rstudio/chromote@3f57897")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo rstudio/chromote@3f57897
#> rlang    (9bed9dd62... -> 94ff8a201...) [GitHub]
#> Rcpp     (1.0.6        -> 1.0.7       ) [CRAN]
#> cpp11    (d761dfc05... -> d8ebaecb1...) [GitHub]
#> jsonlite (NA           -> 1.7.2       ) [CRAN]
#> Installing 2 packages: Rcpp, jsonlite
#> 
#> The downloaded binary packages are in
#>  /var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T//RtmpyK2ZRZ/downloaded_packages
#> Downloading GitHub repo r-lib/rlang@HEAD
#>      checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe102b88199e/r-lib-rlang-94ff8a2/DESCRIPTION’ ...  ✔  checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe102b88199e/r-lib-rlang-94ff8a2/DESCRIPTION’
#>   ─  preparing ‘rlang’:
#>      checking DESCRIPTION meta-information ...  ✔  checking DESCRIPTION meta-information
#>   ─  cleaning src
#>      Warning in system2(command, args, stdout = NULL, stderr = NULL, ...) :
#>      error in running command
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘rlang_0.4.11.9001.tar.gz’
#>      
#> 
#> Downloading GitHub repo r-lib/cpp11@HEAD
#>      checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe1040835b5e/r-lib-cpp11-d8ebaec/DESCRIPTION’ ...  ✔  checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe1040835b5e/r-lib-cpp11-d8ebaec/DESCRIPTION’
#>   ─  preparing ‘cpp11’:
#>      checking DESCRIPTION meta-information ...  ✔  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘cpp11_0.3.1.9000.tar.gz’
#>      
#>      checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe1073a80d04/rstudio-chromote-3f57897/DESCRIPTION’ ...  ✔  checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmpyK2ZRZ/remotesbe1073a80d04/rstudio-chromote-3f57897/DESCRIPTION’
#>   ─  preparing ‘chromote’:
#>      checking DESCRIPTION meta-information ...  ✔  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘chromote_0.0.0.9003.tar.gz’
#>      
#> 

library(chromote)
ChromoteSession$new()
#> Error: Required package curl not found. Please run: install.packages('curl')
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>




----------------------

Using PR:

``` r
remove.packages("curl")
#> Removing package from '/Library/Frameworks/R.framework/Versions/4.0/Resources/library'
#> (as 'lib' is unspecified)
#> Error in find.package(pkgs, lib): there is no package called 'curl'
remotes::install_github("rstudio/chromote#54")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo rstudio/chromote@curl
#> curl (NA -> 4.3.2) [CRAN]
#> Installing 1 packages: curl
#> 
#> The downloaded binary packages are in
#>  /var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T//RtmploOTRM/downloaded_packages
#>      checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmploOTRM/remotesc25f10e3f3cf/rstudio-chromote-9fd0514/DESCRIPTION’ ...  ✔  checking for file ‘/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmploOTRM/remotesc25f10e3f3cf/rstudio-chromote-9fd0514/DESCRIPTION’
#>   ─  preparing ‘chromote’:
#>   ✔  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘chromote_0.0.0.9003.tar.gz’
#>      
#> 
#> Adding 'curl_4.3.2.tgz' to the cache

library(chromote)
ChromoteSession$new()
#> <ChromoteSession>
#>   Public:
#>     Accessibility: list
#>     Animation: list
#>     ApplicationCache: list
#>     Audits: list
#>     BackgroundService: list
#>     Browser: list
#>     CacheStorage: list
#>     Cast: list
#>     close: function (wait_ = TRUE) 
#>     Console: list
#>     CSS: list
#>     Database: list
#>     debug_log: function (...) 
#>     Debugger: list
#>     default_timeout: 10
#>     DeviceOrientation: list
#>     DOM: list
#>     DOMDebugger: list
#>     DOMSnapshot: list
#>     DOMStorage: list
#>     Emulation: list
#>     Fetch: list
#>     get_auto_events: function () 
#>     get_child_loop: function () 
#>     get_parent: function () 
#>     get_session_id: function () 
#>     HeadlessExperimental: list
#>     HeapProfiler: list
#>     IndexedDB: list
#>     init_promise: function () 
#>     initialize: function (parent = default_chromote_object(), width = 992, height = 744, 
#>     Input: list
#>     Inspector: list
#>     invoke_event_callbacks: function (event, params) 
#>     IO: list
#>     is_active: function () 
#>     LayerTree: list
#>     Log: list
#>     mark_closed: function () 
#>     Media: list
#>     Memory: list
#>     Network: list
#>     new_session: function (width = 992, height = 774, targetId = NULL, wait_ = TRUE) 
#>     Overlay: list
#>     Page: list
#>     parent: Chromote, R6
#>     Performance: list
#>     PerformanceTimeline: list
#>     Profiler: list
#>     protocol: list
#>     Runtime: list
#>     Schema: list
#>     screenshot: function (filename = "screenshot.png", selector = "html", cliprect = NULL, 
#>     screenshot_pdf: function (filename = "screenshot.pdf", pagesize = "letter", margins = 0.5, 
#>     Security: list
#>     send_command: function (msg, callback = NULL, error = NULL, timeout = NULL) 
#>     ServiceWorker: list
#>     Storage: list
#>     SystemInfo: list
#>     Target: list
#>     Tethering: list
#>     Tracing: list
#>     view: function () 
#>     wait_for: function (p) 
#>     WebAudio: list
#>     WebAuthn: list
#>   Private:
#>     auto_events: NULL
#>     event_manager: EventManager, R6
#>     init_promise_: NULL
#>     is_active_: TRUE
#>     pixel_ratio: 1
#>     register_event_listener: function (event, callback = NULL, timeout = NULL) 
#>     session_id: A9C1B1D0B33219B5EF5CCCD23D123C3D
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by schloerke** [comment]
With reprexes working as expected, going to merge

**Comment by cderv** [comment]
Thanks @schloerke ! 

In order to 'trick' R CMD CHECK, I believe you could also just add **curl** in NAMESPACE. 

For example, by adding an `@importFrom` with others. 

````diff
diff --git a/R/chromote.R b/R/chromote.R
index 8767709..d8270e9 100644
--- a/R/chromote.R
+++ b/R/chromote.R
@@ -4,6 +4,7 @@
 #' @import promises later
 #' @importFrom fastmap fastmap
 #' @importFrom processx process
+#' @importFrom curl curl
 NULL
````

That way it would be in NAMESPACE and `checking dependencies in R code` would be happy (no more NOTE). This is kind of the same as you solution but it prevent having a dummy function. No more `zzz.R` file.

You may already know that though, and prefer the current solution. Just sharing in case it helps. 

Thanks again !

**Comment by schloerke** [comment]
👍 I didn't know that one would work. Nice!

**Comment by cderv** [comment]
I wasn't sure but I tested it this morning. I'll send you a PR as I have the change ready already

**Pull request merged**
